#!/bin/bash
# Should be linked to .git/hooks/pre-commit

GREEN='\033[0;32m'
REVERT_COLOR='\033[0m'


divider=$(printf "%20s");


echo -e ${GREEN}
echo -e ${divider// /=}
echo -e "SORT IMPORTS"
echo -e ${divider// /=}${REVERT_COLOR}
poetry run isort statistics_server --check
if [ $? != 0 ]; then
    poetry run isort statistics_server
    exit 1
fi

echo -e ${GREEN}
echo -e ${divider// /=}
echo -e "RUN TESTS"
echo -e ${divider// /=}${REVERT_COLOR}
poetry run pytest

echo -e ${GREEN}
echo -e ${divider// /=}
echo -e "RUN LINTING"
echo -e ${divider// /=}${REVERT_COLOR}
poetry run ruff check statistics_server
